### ISSUE TITLE
Is the evaluation for TFTexture correct?

### ISSUE THREAD

**Issue by bopan3** [shamanDevel/DiffDVR#11]
<img width="611" alt="截屏2022-12-08 19 44 04" src="https://user-images.githubusercontent.com/21981916/206438941-59a0ff4a-3134-4ae0-907b-1552b358bcf7.png">
Hi Sebastian,
I wonder if your evaluation for TFTexture is correct.
As the code in the screenshot shows, d = density * R - 0.5.
However, I believe the correct version should be d = density * (R-1). 
If "d = density * R - 0.5", d will equal -0.5 when density equals zero.

**Comment by shamanDevel** [comment]
Hi, good catch. But I think, it has a bigger implication.

If you check, how the TF texture is currently computed, it is consistent. Let `di` be the texel index in {0,1,2,...,R-1}, `d` the density in [0,1].
Then the TF texture is currently computed in https://github.com/shamanDevel/DiffDVR/blob/master/renderer/tf_utils.cpp#L150 by looping over all texels `di`, computing `d=(di+0.5)/R` and querying the control points there. Or in other words, the texels are linearly spaced with a step size of 1/R from 1/2R to (2R-1)/2R.
This is consistent with the "inverse" in the transfer function evaluation.

But perhaps it is better to split the density domain [0,1] into equal-spaced pieces of size 1/(R-1)?
This would give rise then to a change in `tf_utils.cpp`: `d=di/(R-1)`; and the change to `renderer_tf.cuh`: `di=d*(R-1)`, as you proposed.

What do you think?

**Comment by bopan3** [comment]
Hi Sebastian,

Sorry for the late reply. I see. I think it will not be a big deal as long as R is large enough (usually we don't care about places where the density is close to zero). I am curious about if you have any special consideration for adding this "0.5" (which is a magic number for me).

I also wonder whether the gaussian transfer function is the same as the vis2003 paper. 

In your implementation, when multiple gaussian primitives are mixed together, the $total \\ density$ becomes $\sum_{i} ci[3]*ni$, the $total \\ radiant \\ intensity$ becomes $\sum_{i} ci[0:3]*ni$, and the “associated color” during blending will be $total \\ radiant \\ intensity * (1-exp(- total \\ density))$, if we use beerLambert blending.

However, I think maybe the contribution of each gaussian primitive should be calculated separately, in order to simulate "every type of particles giving their own light". i.e. the “associated color” = $\sum_{i}(ci[0:3] * ni * (1-exp(-ci[3] * ni)))$.  

Do you have any special consideration for your choice? (although I believe the implementation difference will not lead to large visual difference for the rendered image unless we deliberately construct some extreme case: e.g. if we mix two gaussian primitives (red gaussian with very low density [r,g,b,density] = [1,0,0,0.000001], and a blue gaussian with high density [r,g,b,density] = [1,0,0,10]) with the same mu and sigma together, the resulting color (in your implementation) will be purple with high density instead of blue with high density).

By the way, these months I keep thinking about how to extend diffDVR for more useful scenarios, can I make some further discussion with you? Maybe with email or other forms of medium instead of github issues (for discussion not related to code issue)? 

Thanks a lot! I really like your series of work!

**Comment by shamanDevel** [comment]
The 0.5 offset comes from the fact, of how the texture sampler in CUDA works. See here: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#linear-filtering, Figure 19, non-normalized indexing.
While not strictly needed for DiffDVR, it is a relict from previous versions of my renderer where I used hardware texture interpolation to query the TF.

The gaussian transfer functions are implemented as I understood the VIS 2003 paper. It might not be the only interpretation, though. I use it more as a more natural form of editing the TF and use the texture TF primarily for optimization.

And sure, you can contact me at:  `sebastian DOT weiss DOT tum AT gmail DOT com`.

**Comment by bopan3** [comment]
Oh I see, thanks!
