### ISSUE TITLE
seek third-party library

### ISSUE THREAD

**Issue by chengdechen** [shamanDevel/DiffDVR#12]
cuMat and cudad in the third-party library are invalid. How to obtain them

**Comment by shamanDevel** [comment]
That's a problem with Github, it does not show repositories that are hosted somewhere else. But cloning it with `git clone -recurse-submodules` should still work.
Anyway, these are the dependencies: 
- https://gitlab.com/shaman42/cuMat
- https://gitlab.com/shaman42/cudad

**Comment by chengdechen** [comment]
thanks
