### ISSUE TITLE
Trouble importing pyrender.py

### ISSUE THREAD

**Issue by swj0418** [shamanDevel/DiffDVR#15]
`
Traceback (most recent call last):
  File "tests/camera/run_entropy2d.py", line 15, in <module>
    from diffdvr import Renderer, CameraOnASphere, Entropy, ColorMatches, Settings, setup_default_settings, \
  File "/opt/DiffDVR/pytests/diffdvr/__init__.py", line 2, in <module>
    from .utils import make_real3, make_real4, \
  File "/opt/DiffDVR/pytests/diffdvr/utils.py", line 9, in <module>
    import pyrenderer
ImportError: /opt/DiffDVR/bin/pyrenderer.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev
`

A similar error on importing pyrenderer was encountered on a docker container running [bopan](https://hub.docker.com/r/bopan/diffdvr_v1). It seems like the program is trying to find the file in `<project_dir>/bin`, but to no avail.

Thank you for providing docker containers @AndreiMiculita, @bopan. I know it's been a while, but did anyone come by this problem?

**Comment by shamanDevel** [comment]
Fascinating that it runs on an ARM-machine. If I look at the file name of the python extension `pyrenderer.cpython-38-x86_64-linux-gnu.so` it was compiled against an x86-architecture.
Such a linker error typically indicates that you have a different Torch version during runtime than during compilation

**Comment by swj0418** [comment]
Thanks for the reply. My mistake, the ARM part is not relevant. I was mistaken.

The problem was solved by installing nvidia-container-toolkit on the host machine.
