### ISSUE TITLE
couldn't find forward_vector.h or forward.h

### ISSUE THREAD

**Issue by SUSIEE01** [shamanDevel/DiffDVR#3]
Hi, I'm tring to complier DiffDVR. But it says "fatal error: forward_vector.h: No such file or directory" and "fatal error: forward.h: No such file or directory". How can I figure it out? Your answer will help me a lot!!!

![微信截图_20220515212849](https://user-images.githubusercontent.com/90890796/168475375-a3e81f75-7933-448e-890e-0f26c7815435.png)

**Comment by shamanDevel** [comment]
Hi, sorry that I saw it so late.
The files forward_vector.h and forward.h are part of the submodule “cudad” in third-party/cudad. Was this submodule cloned successfully? Is there anything inside this folder? Similarly, are all the other submodules cloned correctly as well, check e.g. cuMat as well.

**Comment by shamanDevel** [comment]
cudad and cuMat aren't hosted on Github, they are hosted on Gitlab. For some reasons, the Github web interface only shows submodules hosted on Github as well.
If you haven't cloned the repository with submodules included (`git clone --recurse-submodules https://github.com/shamanDevel/DiffDVR.git`), you can fix this afterward by calling
`git submodule update --init` in the root directory of your local clone.

**Comment by SUSIEE01** [comment]
It works! 
But I meet some new errors now...I'll try to solve it myself first!
thanks for your reply again!

**Comment by shamanDevel** [comment]
Good to hear! Then I would close this issue as the problem with the missing forward_vector.h is fixed.
If you need help with the new errors you mentioned, just open another issue. I'll gladly help ;)
