### ISSUE TITLE
environment.yml and requirement.txt for Windows?

### ISSUE THREAD

**Issue by bopan3** [shamanDevel/DiffDVR#6]
I am tring to run diffDVR on window10 platform. However, when I run "conda env create -f environment.yml", I find there are about 10 packages not resolved by conda, and I think they are only support for linux system. Is there a "environment.yml" file for windows platform? 
BTW, diffDVR is a nice work! I decide to spend some time to realy understand it and use it to build something interesting!

**Comment by shamanDevel** [comment]
Hi, on Windows I'm using regular Python with virtualenv, not anaconda. Can you try the `requirements.txt` file? That should be a freeze of my pip packages on Windows.
Regardless, you could also simply install the packages manually. I don't use many dependencies: PyTorch 1.8 (obviously), numpy, matplotlib, h5py, tqdm, pillow.

The difficult part is installing the C++/CUDA extension for PyTorch, as this is closely tied to your local CUDA SDK installation and PyTorch version. Make sure that the correct PyTorch and CUDA version is found when you run CMake!

**Comment by bopan3** [comment]
I got it. Thanks a lot for your fast and helpful reply!
