### ISSUE TITLE
unknown cmake command “cmrc_add_resource_library”

### ISSUE THREAD

**Issue by chengdechen** [shamanDevel/DiffDVR#9]
cmake Error at CMakeLists.txt:193(cmrc_add_resource_library):
unknown cmake command "cmrc_add_resource_library"

**Comment by bopan3** [comment]
Hi,
Check if "CMakeRC.cmake" file in your build folder is empty ("cmrc_add_resource_library" should be defined there).
if it's empty, just manually download the file and copy it to the right place.
To do this, you can replace one line in the CMakeList.txt:
replace 
```
file(DOWNLOAD "https://raw.githubusercontent.com/vector-of-bool/cmrc/master/CMakeRC.cmake"
				"${CMAKE_BINARY_DIR}/CMakeRC.cmake")
```
to 
```
file(COPY /YourFolderForDownloadCMakeRC/CMakeRC.cmake DESTINATION /YourFolderForDiffDVR/DiffDVR/build/)
```
remember to replace the folder "YourFolder..." to your own folder

**Comment by shamanDevel** [comment]
Hi bopan3, thanks for helping out.
Chengdechen, did you get any additional info or warning messages during the CMake run, e.g. a notification that the download of CMakeRC failed?

**Comment by shamanDevel** [comment]
Hi @chengdechen , have you managed to resolve the issue with missing CMRC?

**Comment by chengdechen** [comment]
> 

yes,thanks
